name = "cbf-worker"
compatibility_date = "2025-07-04"
main = "src/index.js"
workers_dev = true

[vars]
IMAGEKIT_URL_ENDPOINT = "https://ik.imagekit.io/cyanbluefilms"

# Add secrets via:
# wrangler secret put IMAGEKIT_PRIVATE_KEY

[dev]
ip = "localhost"
port = 8787
local_protocol = "http"

[observability]
enabled = true
head_sampling_rate = 1