name = "cbf-worker"
compatibility_date = "2024-06-01"
main = "src/index.js"
workers_dev = true

[vars]
IMAGEKIT_URL_ENDPOINT = "https://ik.imagekit.io/cyanbluefilms"

# Add secrets via:
# wrangler secret put IMAGEKIT_PRIVATE_KEY